Add refget proxy k8s manifests.
Ensembl/ensembl-client pull request #752
Opened 2022-05-18 13:22 UTC by Mehrnaz-Charkhchi

## Description
Replace GAA refget with refget proxy in review branches to be able to retrieve genomic sequences from ENA refget.

## Related JIRA Issue(s)
[JIRA
](https://www.ebi.ac.uk/panda/jira/browse/EWB-182)

## Deployment URL(s)
http://refget-proxy-review-template.review.ensembl.org

## Views affected
None
Affects only CI/CD pipeline

2022-05-18 14:57 UTC, azangru approved these changes
~I trust that the yaml file is correct.~

~Please remember to merge `refget-proxy-manifests` into `wp-k8s-review` and undo the change in line 17 of the yaml file.~

Well, trust but verify :-) There is still an error when requesting a genomic sequence:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/6834224/169075017-33c50500-08f3-4201-bde9-7cf503209a49.png">

Steps to replicate:

UI:
- select a species and go to genome browser page
- open the drawer
- click on the "sequence" dropdown to view the sequence
- the genomic sequence fails to load

Direct url:
GET http://refget-proxy-review-template.review.ensembl.org/api/refget/sequence/a5437debe2ef9c9ef8f3ea2874ae1d82?start=32315086&end=32400268 — 404 error

2022-05-18 15:13 UTC, azangru requested changes
Please make sure that refget proxy can fetch genomic sequences.

2022-08-23 14:52 UTC, veidenberg commented
The review app is now working and I [updated the ingress](https://gitlab.ebi.ac.uk/ensembl-web/ensembl-k8s-manifests/-/blob/refget-proxy-manifests/ensembl_refget_proxy_ingress.yaml#L6) to reflect the fix. This PR needs the following changes before merging:
1. Merge `refget-proxy-manifests` branch to `wp-k8s-review` branch
2. Revert branch name back to `wp-k8s-review` in `.setup-review-remplate.yaml`

2022-08-23 14:52 UTC, veidenberg commented on gitlab-ci-templates/.setup-review-template.yaml
> +    - git -C ensembl-k8s-manifests/ checkout refget-proxy-manifests
Please revert this change before merging.

2022-08-23 14:53 UTC, veidenberg approved these changes
The review app is now working and I [updated the ingress](https://gitlab.ebi.ac.uk/ensembl-web/ensembl-k8s-manifests/-/blob/refget-proxy-manifests/ensembl_refget_proxy_ingress.yaml#L6) to reflect the fix. This PR needs the following changes before merging:
- Merge `refget-proxy-manifests` branch to `wp-k8s-review` branch in the [manifests repo](https://gitlab.ebi.ac.uk/ensembl-web/ensembl-k8s-manifests)
- Revert the branch name back to `wp-k8s-review` in `.setup-review-remplate.yaml`

2022-08-24 08:41 UTC, Mehrnaz-Charkhchi commented
> The review app is now working and I [updated the ingress](https://gitlab.ebi.ac.uk/ensembl-web/ensembl-k8s-manifests/-/blob/refget-proxy-manifests/ensembl_refget_proxy_ingress.yaml#L6) to reflect the fix. This PR needs the following changes before merging:
> 
> * Merge `refget-proxy-manifests` branch to `wp-k8s-review` branch in the [manifests repo](https://gitlab.ebi.ac.uk/ensembl-web/ensembl-k8s-manifests)
> * Revert the branch name back to `wp-k8s-review` in `.setup-review-remplate.yaml`

@veidenberg Could you please let me know where are the ingress files? I want to prevent the feature deployments from GAA refget.

2022-08-24 08:46 UTC, veidenberg commented
@Mehrnaz-Charkhchi the ingress that I updated and is used in this PR is [here](https://gitlab.ebi.ac.uk/ensembl-web/ensembl-k8s-manifests/-/blob/refget-proxy-manifests/ensembl_refget_proxy_ingress.yaml#L6).

2022-08-26 13:36 UTC, merged