Move grch38 to top of blast species list
Ensembl/ensembl-client pull request #863
Opened 2022-10-26 08:31 UTC by jyothishnt

## Description
GRCh38 needs to given more prominence and it should be in the top of the list of species to be selected in the right hand pane of the BLAST form. GRCh37 needs to be moved just below it.
This is a temporary fix on the client side. Species list should eventually come from the backend.

## Related JIRA Issue(s)
https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-1746

## Deployment URL(s)
http://reorder-blast-species-list.review.ensembl.org

## Views affected
Blast

2022-10-26 15:36 UTC, azangru approved these changes
My immediate question was why pass that array through the sorting function; why not just hard-code the order of the species in the array. I am not convinced the implementation of the sorting function is even correct. But then, it's a strange file that will sooner or later be deleted...

2022-10-27 12:24 UTC, imransl approved these changes

2022-10-27 13:17 UTC, azangru requested changes
Since we decided to use the popular species endpoint from the species selector to get the species list (see [ENSWBSITES-1773](https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-1773)), there is no point in merging this pull request. Either use the same PR for ENSWBSITES-1773, or create a new PR (and we will close this one when the other one is accepted).

2022-11-08 14:23 UTC, azangru commented
This PR is superseded by https://github.com/Ensembl/ensembl-client/pull/871

2022-11-08 14:23 UTC, closed without merging